# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ('ingredient_name',),
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=256)),
                ('spicy', models.CharField(max_length=32)),
                ('price_s', models.CharField(max_length=32)),
                ('price_m', models.CharField(max_length=32)),
                ('price_l', models.CharField(max_length=32)),
                ('ingredients', models.ManyToManyField(to='restaurants.Ingredients')),
            ],
            options={
                'ordering': ('meal_name',),
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=64)),
                ('open_at_mon', models.CharField(max_length=32)),
                ('close_at_mon', models.CharField(max_length=32)),
                ('open_at_tue', models.CharField(max_length=32)),
                ('close_at_tue', models.CharField(max_length=32)),
                ('open_at_wed', models.CharField(max_length=32)),
                ('close_at_wed', models.CharField(max_length=32)),
                ('open_at_thu', models.CharField(max_length=32)),
                ('close_at_thu', models.CharField(max_length=32)),
                ('open_at_fri', models.CharField(max_length=32)),
                ('close_at_fri', models.CharField(max_length=32)),
                ('open_at_sat', models.CharField(max_length=32)),
                ('close_at_sat', models.CharField(max_length=32)),
                ('open_at_sun', models.CharField(max_length=32)),
                ('close_at_sun', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
        ),
    ]
